### ISSUE TITLE
Touch behaviour on desktop menu (≥ 992px)

### ISSUE THREAD

**Issue by OlliZabal** [sschreier/SschreierDropdownMenu#2]
Fantastic plugin - many thanks!!!

I did just recognized one behavior (not really an issue) on a touch device while displaying the normal desktop menu (≥ 992px screen size):
-> a touch does immediately fire a "click"
-> on the default Shopware menu a touch on a "main-navigation-link" first opens it's corresponding "navigation-flyout"

It would be great to have this behavior also on your Dropdownmenu plugin. Any thoughts?

**Comment by sschreier** [comment]
Hello,

thanks for ticket. I don't know what you mean - when I have more than one submenu level, for example "Bekleidung" with the submenus "Damen" and "Herren" and "Damen" with the submenus "Hosen", "Jeans" and "Shorts", I can click on each level on my tablet (iPad landscape mode over 992 pixel screen size). When i click / touch on the same menu point a second time, this category is opened - it is the same behaviour like in the normal flyout menu.

The behaviour of the plugin doesn't come from the plugin, because the plugin used the dropdown script from shopware. 

Best regards
